# Generated by Django 2.2 on 2020-09-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('packages', models.CharField(max_length=50)),
                ('specialoffer', models.CharField(max_length=50)),
            ],
        ),
    ]
