# Generated by Django 2.2 on 2020-09-10 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='phonecode',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='footer',
            name='phonenumber',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
