# Generated by Django 2.2 on 2020-09-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20200910_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serv1_heading', models.CharField(max_length=200)),
                ('serv1_text', models.CharField(max_length=200)),
                ('serv2_heading', models.CharField(max_length=200)),
                ('serv2_text', models.CharField(max_length=200)),
                ('serv3_heading', models.CharField(max_length=200)),
                ('serv3_text', models.CharField(max_length=200)),
            ],
        ),
    ]
