# Generated by Django 2.2 on 2020-09-10 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='specialoffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_heading', models.CharField(max_length=200)),
                ('special_star', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('special_review_count', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('special_days', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('special_nights', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('special_person', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('special_accomodation', models.CharField(max_length=10)),
                ('special_transportation', models.CharField(max_length=10)),
                ('special_food', models.CharField(max_length=10)),
                ('offer_detail', models.CharField(max_length=200)),
                ('button_1', models.CharField(max_length=20)),
                ('button_2', models.CharField(max_length=20)),
                ('offer_heading', models.CharField(max_length=20)),
                ('percent_off', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('special_price', models.PositiveIntegerField()),
                ('special_type', models.CharField(max_length=20)),
                ('special_type_price', models.PositiveIntegerField()),
            ],
        ),
    ]
