# Generated by Django 2.2 on 2020-09-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_specialoffer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='packages',
            new_name='package',
        ),
        migrations.RenameModel(
            old_name='services',
            new_name='service',
        ),
    ]
