# Generated by Django 2.2 on 2020-09-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_auto_20200910_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_heading', models.CharField(max_length=200)),
                ('client_text', models.CharField(max_length=200)),
                ('customer_name_1', models.CharField(max_length=200)),
                ('customer_review_1', models.CharField(max_length=200)),
                ('customer_location_1', models.CharField(max_length=200)),
                ('customer_review_2', models.CharField(max_length=200)),
                ('customer_name_2', models.CharField(max_length=200)),
                ('customer_location_2', models.CharField(max_length=200)),
                ('customer_name_3', models.CharField(max_length=200)),
                ('customer_review_3', models.CharField(max_length=200)),
                ('customer_location_3', models.CharField(max_length=200)),
                ('customer_name_4', models.CharField(max_length=200)),
                ('customer_review_4', models.CharField(max_length=200)),
                ('customer_location_4', models.CharField(max_length=200)),
                ('customer_name_5', models.CharField(max_length=200)),
                ('customer_review_5', models.CharField(max_length=200)),
                ('customer_location_5', models.CharField(max_length=200)),
                ('customer_name_6', models.CharField(max_length=200)),
                ('customer_review_6', models.CharField(max_length=200)),
                ('customer_location_6', models.CharField(max_length=200)),
                ('customer_name_7', models.CharField(max_length=200)),
                ('customer_review_7', models.CharField(max_length=200)),
                ('customer_location_7', models.CharField(max_length=200)),
            ],
        ),
    ]
