# Generated by Django 2.2 on 2020-09-10 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_clientreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_heading', models.CharField(max_length=200)),
                ('dest_text', models.CharField(max_length=200)),
                ('dest1_name', models.CharField(max_length=200)),
                ('no_tours_1', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('no_places_1', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('dest2_name', models.CharField(max_length=200)),
                ('no_tours_2', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('no_places_2', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('dest3_name', models.CharField(max_length=200)),
                ('no_tours_3', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('no_places_3', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('dest4_name', models.CharField(max_length=200)),
                ('no_tours_4', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('no_places_4', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('dest5_name', models.CharField(max_length=200)),
                ('no_tours_5', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('no_places_5', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('dest6_name', models.CharField(max_length=200)),
                ('no_tours_6', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('no_places_6', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
            ],
        ),
    ]
