# Generated by Django 2.2 on 2020-09-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='dest1_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
