# Generated by Django 2.2 on 2020-09-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_package_dest1_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='dest2_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='package',
            name='dest3_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='package',
            name='dest4_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='package',
            name='dest5_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='package',
            name='dest6_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
