# Generated by Django 2.2 on 2020-09-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_specialoffer_offer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreview',
            name='customer1_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='customer2_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='customer3_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='customer4_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='customer5_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='customer6_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='clientreview',
            name='customer7_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
