# Generated by Django 2.2 on 2020-09-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_auto_20200912_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='fac_href',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
