# Generated by Django 2.2 on 2020-09-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_footer_fac_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='insta_href',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='twitter_href',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
