# Generated by Django 2.2 on 2020-09-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_auto_20200913_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='main_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
