# Generated by Django 2.2 on 2020-09-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_places'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='places',
            new_name='place',
        ),
    ]
