# Generated by Django 3.1.2 on 2020-10-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0022_offer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='image',
            new_name='day10_img',
        ),
        migrations.AddField(
            model_name='offer',
            name='day10_place',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day10_text',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day11_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='day11_place',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day11_text',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day12_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='day12_place',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day12_text',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day13_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='day13_place',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day13_text',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day14_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='day14_place',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day14_text',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day15_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='day15_place',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day15_text',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day16_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='day16_place',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day16_text',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day17_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='day17_place',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day17_text',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day18_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='day18_place',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day18_text',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day19_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='day19_place',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day19_text',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day1_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='day1_place',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day1_text',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day20_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='day20_place',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day20_text',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day2_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='day2_place',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day2_text',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day3_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='day3_place',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day3_text',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day4_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='day4_place',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day4_text',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day5_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='day5_place',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day5_text',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day6_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='day6_place',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day6_text',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day7_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='day7_place',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day7_text',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day8_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='day8_place',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day8_text',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day9_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='day9_place',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='day9_text',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
