# Generated by Django 3.1.2 on 2021-02-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0024_auto_20201027_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
