# Generated by Django 3.1.2 on 2021-03-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0025_offer_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='day20_img',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='day10_img',
            new_name='image3',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='day11_img',
            new_name='image4',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='day12_img',
            new_name='image5',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='day13_img',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='day14_img',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='day15_img',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='day16_img',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='day17_img',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='day18_img',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='day19_img',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='day1_img',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='day2_img',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='day3_img',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='day4_img',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='day5_img',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='day6_img',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='day7_img',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='day8_img',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='day9_img',
        ),
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
