# Generated by Django 3.1.2 on 2021-03-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0028_auto_20210306_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
